"""First migration

Revision ID: 4f82bf4dc4e3
Revises: None
Create Date: 2014-11-16 10:52:22.555466

"""

# revision identifiers, used by Alembic.
revision = '4f82bf4dc4e3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
